Client1:
  - postgres://idknfcahjkdeew:96d23cee44a703633bd5f2176a4522ca5c420a526795c71de309ed3ed68ef382@ec2-54-158-1-189.compute-1.amazonaws.com:5432/d8vqkjri4dbsjo
  #- postgresql://suhas:qwerty@localhost:5432/Client1
  - Client1
#- mysql+pymysql://root:qwerty@localhost/newnormal?charset=utf8
#- newnormal

Client2:
  - postgres://hvdqeccloviaqz:7570a39b5330237a905a25665d201d03ca25de356eff1522f94b50ced18bfa4c@ec2-54-85-13-135.compute-1.amazonaws.com:5432/d38blvmp22htul
  #- postgresql://suhas:qwerty@localhost:5432/Client2
  - Client2

#- mysql+pymysql://root:qwerty@localhost/new_tenant?charset=utf8
#- new_tenant
