Client1:
  - postgres://hvdqeccloviaqz:7570a39b5330237a905a25665d201d03ca25de356eff1522f94b50ced18bfa4c@ec2-54-85-13-135.compute-1.amazonaws.com:5432/Client1
  #- postgresql://suhas:qwerty@localhost:5432/Client1
  - Client1
#- mysql+pymysql://root:qwerty@localhost/newnormal?charset=utf8
#- newnormal

Client2:
  - postgres://hvdqeccloviaqz:7570a39b5330237a905a25665d201d03ca25de356eff1522f94b50ced18bfa4c@ec2-54-85-13-135.compute-1.amazonaws.com:5432/Client2
  #- postgresql://suhas:qwerty@localhost:5432/Client2
  - Client2

#- mysql+pymysql://root:qwerty@localhost/new_tenant?charset=utf8
#- new_tenant
